### ISSUE TITLE
Crash when triggering bug reporter

### ISSUE THREAD

**Issue by alexfu** [Buglife/buglife-android#1]
**Device**: Pixel XL
**SDK Version**: 0.9.10
**Android Version**: 7.1.2

When triggering the crash reporter via shake or screenshot, I get a crash from the SDK...

```
AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
AndroidRuntime:        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
AndroidRuntime:        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
AndroidRuntime:        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
AndroidRuntime:        at android.app.Dialog.show(Dialog.java:329)
AndroidRuntime:        at com.buglife.sdk.Client.showAlertDialog(Client.java:349)
AndroidRuntime:        at com.buglife.sdk.Client.onScreenshotTaken(Client.java:294)
AndroidRuntime:        at com.buglife.sdk.Client.access$200(Client.java:65)
AndroidRuntime:        at com.buglife.sdk.Client$1.onShake(Client.java:258)
AndroidRuntime:        at com.buglife.sdk.ShakeDetector.onSensorChanged(ShakeDetector.java:74)
AndroidRuntime:        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:699)
AndroidRuntime:        at android.os.MessageQueue.nativePollOnce(Native Method)
AndroidRuntime:        at android.os.MessageQueue.next(MessageQueue.java:323)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:136)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

After looking into it (https://github.com/Buglife/buglife-android/blob/master/src/main/java/com/buglife/sdk/Client.java#L321), `AlertDialog`s cannot be used with an Application context.

**Comment by alexfu** [comment]
Potential fix that I can think of immediately is to launch an invisible Activity that then shows the AlertDialog.

**Comment by schukin** [comment]
This should be fixed by 585eac9. Please update to buglife-android v0.9.11.

Also, thanks for reporting this! 😎

**Comment by alexfu** [comment]
@schukin I'm still getting this crash. Did some further digging and discovered that it's a combination of a couple things.

1. Having `compileSdkVersion` and `targetSdkVersion` set to 26.
2. Setting `WindowManager.LayoutParams.TYPE_TOAST` on dialog window. (https://github.com/Buglife/buglife-android/blob/master/src/main/java/com/buglife/sdk/Client.java#L347)

Bumping down my `compileSdkVersion` and `targetSdkVersion` to 25 seemed to have resolved the issue but once API 26 is out of developer preview, this might re-surface with others.

Not entirely sure if this crash is expected or a bug so I filed an Android issue here: https://issuetracker.google.com/issues/64060444

**Comment by schukin** [comment]
Whoops! Looks like we closed this prematurely, sorry about that. Investigating...

**Comment by schukin** [comment]
K, this should be *actually* fixed with 9b78c86 (published in buglife-android v0.9.12). Verified the fix on our end, but please let us know if you run into any other issues. Thanks for your help investigating this!
